#!/bin/bash

function extract 
{
    sed -n '/^\/\/\/ /s,/// ,,p' $1
}

echo "" > src/adaptors.md

extract ../fit/compose.h >> src/adaptors.md
extract ../fit/conditional.h >> src/adaptors.md
extract ../fit/fix.h >> src/adaptors.md
extract ../fit/fuse.h >> src/adaptors.md
extract ../fit/implicit.h >> src/adaptors.md
extract ../fit/invoke.h >> src/adaptors.md
extract ../fit/lazy.h >> src/adaptors.md
extract ../fit/match.h >> src/adaptors.md
extract ../fit/mutable.h >> src/adaptors.md
extract ../fit/on.h >> src/adaptors.md
extract ../fit/partial.h >> src/adaptors.md
extract ../fit/pipable.h >> src/adaptors.md
extract ../fit/placeholders.h >> src/adaptors.md
extract ../fit/protect.h >> src/adaptors.md
extract ../fit/reveal.h >> src/adaptors.md
extract ../fit/static.h >> src/adaptors.md
extract ../fit/variadic.h >> src/adaptors.md

echo "" > src/functions.md

extract ../fit/always.h >> src/functions.md
extract ../fit/identity.h >> src/functions.md

echo "" > src/utilities.md

extract ../fit/args.h >> src/utilities.md
extract ../fit/is_callable.h >> src/utilities.md
extract ../fit/returns.h >> src/utilities.md
