#!/bin/bash

function extract 
{
    sed -n '/^\/\/\/ /s,/// ,,p' ../fit/$1.h > src/$1.md
}

extract always
extract apply
extract apply_eval
extract args
extract capture
extract compose
extract conditional
extract eval
extract fix
extract flip
extract function
extract identity
extract implicit
extract indirect
extract infix
extract is_callable
extract lambda
extract lazy
extract lift
extract match
extract mutable
extract by
extract pack
extract partial
extract pipable
extract placeholders
extract protect
extract result
extract returns
extract reveal
extract static
extract tap
extract unpack
extract variadic
